### ISSUE TITLE
Ta bort namn ur Epilogen

### ISSUE THREAD

**Issue by chrokh** [webbraket/webbraket.se#24]
Och skriv istället att vi är ett team av studenter, lärare och forskare vid Uppsala Universitets program Informationssystem. Lite såsom i README:n för repot:
https://github.com/webbraket/webbraket.se/blob/master/README.markdown

**Comment by chrokh** [comment]
Alternativt så listar vi alla i core team för att man ska ha möjligheten att göra promotion för sig själv. Jag skulle förstås gärna se mig själv listad då det driver trafik till t.ex. min Twitter :) Vad säger ni?

ping @anton-g @johnlar @llundgren @mv00 @JWesslen

Detta kan ju vara vettigt eftersom det är ett open source-projekt. Så ett sätt att få payback för sitt effort är ju denna self-promotion. Om någon i framtiden lämnar Webbraket och ger sig ut i industrin så kan man bli listad under ytterligare en rubrik. Typ Past Contributors.

**Comment by chrokh** [comment]
Toppen att ni är på detta! :) Kör vi på att lista namn eller vad tycker ni? Isåfall borde vi ju samla ihop affiliated information. Dvs hur folk vill bli länkade. Jag vill t.ex. gärna att min länk pekar på christopherokhravi.se men andra kanske vill ha sin mail, twitter, linkedin eller liknande. Den diskussionen skulle vi ju kunna ta på Slack men låt oss först bestämma huruvida vi listar info eller inte här.

**Comment by anton-g** [comment]
Tycker det är vettigt att lista namn med länk till något. Alltid trevligt att få en liten "fjäder i hatten". :)

**Comment by mv00** [comment]
Ja jag tycker det är väldigt bra med en namnlista med current och past contributors samt länka till valfri sida. Vi tänkte bara länka git profilen by default, men vill man ha något annat så är det bara skriva till mig på Slack.

**Comment by chrokh** [comment]
Resolved by #41 .
