### ISSUE TITLE
Ta bort information om teams i readme eftersom vi arbetar mer fritt?

### ISSUE THREAD

**Issue by chrokh** [webbraket/webbraket.se#47]
Har vi koncensus kring detta?

Jag vill alltså ta bort listan som följer efter texten "Vi arbetar för nuvarande i nedan team" i `README.markdown`.

**Comment by anton-g** [comment]
Jag håller med. Om vi skulle börja arbeta i team så är det ju inte supersvårt att lägga till det igen, men just nu känns det onödigt att ha med.
